/* eslint-disable no-console */
/**
 * @fileoverview Writes resume/atsText.generated.ts: the ATS résumé as plain text, the only source
 * of facts for /api/fit and the résumé part of /api/chat. Runs after `npm install` and in `npm run build`.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { RESUME_DOCUMENTS } from '../resume/documents';
import { findResumeTextProblems, resumeTextForAi } from '../resume/plainText';

const root = process.cwd();
const source = RESUME_DOCUMENTS.ats.src;
const text = resumeTextForAi(readFileSync(resolve(root, source), 'utf8'));

const problems = findResumeTextProblems(text);
if (problems.length > 0) {
  console.error(`Can't build the résumé text from ${source}:\n- ${problems.join('\n- ')}`);
  process.exit(1);
}

writeFileSync(
  resolve(root, 'resume/atsText.generated.ts'),
  `// Generated by \`npm run resume:text\` from ${source}. Do not edit.\n` +
    `export const RESUME_TEXT = ${JSON.stringify(text)};\n`
);
console.log(`Wrote resume/atsText.generated.ts (${text.length} characters).`);
